version: '3'

services:
  database:
    image: amazon/dynamodb-local
    hostname: dynamodb
    container_name: dynamo_db
    ports: 
      - 8000:8000
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
    networks:
      - network
  application:
    image: toeat-api
    build: .
    ports:
      - 8080:8080
    links:
      - database
    networks:
      - network
networks:
  network:
    driver: bridge

