version: '3'

services:
  database:
    image: amazon/dynamodb-local
    hostname: dynamodb
    container_name: dynamo_db
    ports: 
      - 27017:27017
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
